CREATE DATABASE vet_clinic;
CREATE TABLE animals (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50) NOT NULL, date_of_birth DATE NOT NULL, escape_attempts INT NOT NULL, neutered BOOLEAN NOT NULL, weight_kg DECIMAL(18, 2));
ALTER TABLE animals ADD species VARCHAR(100);
create table owners(id int generated by default as identity primary key, full_name varchar(50) not null, age int not null);
create table species (id int generated by default as identity primary key, name varchar(50));
alter table animals drop column species;
alter table animals add column species_id int;
alter table animals add column species_id int;
alter table animals add constraint fk_animals foreign key (species_id) references species(id);
alter table animals add column owner_id int;
alter table animals add constraint fk_owner foreign key (owner_id) references owners(id);
create table vets (id int generated by default as identity primary key, name varchar(50) not null, age int not null, date_of_graduation date not null);
create table specialization (vets_id int references vets(id), species_id int references species(id), primary key (vets_id, species_id));
create table visits (id int generated by default as identity, animals_id int references animals(id), vets_id int references vets(id), date_of_visits date not null, primary key (id, animals_id, vets_id));

--branch performance audit
-- Add an email column to your owners table
ALTER TABLE owners ADD COLUMN email VARCHAR(120);
