CREATE DATABASE vet_clinic;
CREATE TABLE animals (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(50) NOT NULL, date_of_birth DATE NOT NULL, escape_attempts INT NOT NULL, neutered BOOLEAN NOT NULL, weight_kg DECIMAL(18, 2));
ALTER TABLE animals ADD species VARCHAR(100);
create table owners(id int generated by default as identity primary key, full_name varchar(50) not null, age int not null);
create table species (id int generated by default as identity primary key, name varchar(50));